module: feature-request-sample
runtime: python27
threadsafe: true

handlers:

- url: /front
  static_dir: front
  secure: always
  application_readable: true

- url: /.*
  script: back.api.app
  secure: always

