module: feature-request-sample
runtime: python27
threadsafe: true

handlers:

- url: /api.*
  script: back.api.app
  secure: always

- url: /
  static_files: front/app.html
  upload: front\/app\.html
  secure: always

- url: /
  static_dir: front
  secure: always
  application_readable: true



