module: feature-request-sample
runtime: python27
threadsafe: true

handlers:

  - url: .*
    script: back.api.app
    secure: always

error_handlers:

  - file: error/ourErrorError.html

  - error_code: over_quota
    file: error/viewOverQuota.html

  - error_code: dos_api_denial
    file: error/viewDOSApiDenial.html

  - error_code: timeout
    file: error/viewTimeout.html

builtins:

  - appstats: on



